<?php
/**
 * @file
 * Commerce add to cart confirmation module.
 */

/**
 * Implements hook_page_attachments().
 */
function commerce_add_to_cart_confirmation_page_attachments(array &$attachments) {
  if (drupal_get_messages('commerce-add-to-cart-confirmation', FALSE)) {
    $attachments['#attached']['library'][] = 'commerce_add_to_cart_confirmation/commerce_add_to_cart_confirmation';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function commerce_add_to_cart_confirmation_preprocess_views_view(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  if ($view->storage->id() == 'confirm_message_product_display') {
    $variables['title'] = [
      '#type' => 'markup',
      '#markup' => '<div class="added-product-title">' . $view->getTitle() . '</div>',
    ];
  }
}
